---
##
# role main options
##

python_24: false
python_26: false
python_27: false
python_31: false
python_32: false
python_33: false
python_34: false
python_35: false
python_36: false
python_37: false
python_38: false
python_39: false
python_310: false
python_311: false
python_312: true
python_313: false

pillow: false
lxml: false

# fine grained settings
base_install_folder: "/srv"
